export const popularPlants = [
  {
    id: 101,
    title: "Fiddle Leaf Fig (Ficus lyrata)",
    markedPrice: 79.99,
    price: 60.0,
    quantity: 1,
    description:
      "This trendy indoor plant is known for its large, glossy leaves that make a bold statement in any room. It thrives in bright, indirect light and needs consistent moisture to stay healthy.",
    benefits: [],
    size: ["small", "medium", "large"],
    place: "indoor",
    tag: "best seller",
    reviewsCount: 145,
    rating: 4.2,
    preOrderStatus: true,
    imgs: [
      "https://res.cloudinary.com/di83yoe1d/image/upload/v1731051640/shopyournursery/ydlpihohdpzz8fccgwpo.png",
      "https://res.cloudinary.com/di83yoe1d/image/upload/v1731051606/shopyournursery/szecpt2ma40qxorgb5vx.jpg",
      "https://res.cloudinary.com/di83yoe1d/image/upload/v1731051656/shopyournursery/hc4bhfojyl4grkcqjryq.jpg",
      "https://res.cloudinary.com/di83yoe1d/image/upload/v1731051662/shopyournursery/xmcjqoq9xxtcnntqeiew.jpg",
    ],
  },
  {
    id: 102,
    title: "Snake Plant (Sansevieria trifasciata)",
    markedPrice: 30.99,
    price: 25.0,
    quantity: 0,
    description:
      "A hardy, low-maintenance plant that tolerates neglect. It thrives in low light and helps purify the air, making it perfect for bedrooms or offices.",
    benefits: [],
    size: ["small", "medium", "large"],
    place: "indoor",
    tag: "best seller",
    reviewsCount: 145,
    rating: 4.2,
    preOrderStatus: false,
    imgs: [
      "https://res.cloudinary.com/di83yoe1d/image/upload/v1731051881/shopyournursery/hwsxrvsuzlu1opqhnxrb.png",
      "https://res.cloudinary.com/di83yoe1d/image/upload/v1731051891/shopyournursery/juugfpenqdcibum2ygvo.png",
      "https://res.cloudinary.com/di83yoe1d/image/upload/v1731051901/shopyournursery/onocd1qn8vrjsnbepo0s.png",
      "https://res.cloudinary.com/di83yoe1d/image/upload/v1731051909/shopyournursery/z8rngbzs9lqol4k9b7c2.jpg",
    ],
  },
  {
    id: 103,
    title: "Peace Lily (Spathiphyllum)",
    markedPrice: 250.99,
    price: 200,
    quantity: 1,
    description:
      "A popular choice for indoor spaces, the Peace Lily features elegant white blooms and is known for its air-purifying properties. It prefers low to medium light and moist soil.",
    benefits: [],
    size: ["small", "medium", "large"],
    place: "indoor",
    tag: "best seller",
    reviewsCount: 145,
    rating: 4.2,
    preOrderStatus: true,
    imgs: [
      "https://res.cloudinary.com/di83yoe1d/image/upload/v1731052028/shopyournursery/mlaitfe4uxl1ht3brwre.jpg",
      "https://res.cloudinary.com/di83yoe1d/image/upload/v1731052037/shopyournursery/t7l7z3sjtdvbhgwklzvv.png",
      "https://res.cloudinary.com/di83yoe1d/image/upload/v1731052047/shopyournursery/sdphrzqphkzh7y0qh1p8.png",
      "https://res.cloudinary.com/di83yoe1d/image/upload/v1731052050/shopyournursery/lnsrmqgtsm8vzjt1ondb.png",
    ],
  },
  {
    id: 104,
    title: "Monstera Deliciosa",
    markedPrice: 60.99,
    price: 45.0,
    quantity: 0,
    description:
      "Known for its iconic split leaves, the Monstera is a favorite among plant enthusiasts. It grows best in bright, indirect light and requires regular watering.",
    benefits: [],
    size: ["small", "medium", "large"],
    place: "indoor",
    tag: "best seller",
    reviewsCount: 145,
    rating: 4.2,
    preOrderStatus: true,
    imgs: [
      "https://res.cloudinary.com/di83yoe1d/image/upload/v1731052368/shopyournursery/wgp8hn7oku1mgvmu5zr1.jpg",
      "https://res.cloudinary.com/di83yoe1d/image/upload/v1731052377/shopyournursery/ev6khi4okp2bcffxi6po.png",
      "https://res.cloudinary.com/di83yoe1d/image/upload/v1731052392/shopyournursery/sf3xkncuyzklqrlxgpfo.png",
    ],
  },
  {
    id: 105,
    title: "Pothos",
    markedPrice: 30.99,
    price: 15.0,
    quantity: 3,
    description:
      "This fast-growing trailing plant is perfect for hanging baskets or as a climber. It's very forgiving and thrives in low light with minimal care.",
    benefits: [],
    size: ["small", "medium", "large"],
    place: "indoor",
    tag: "best seller",
    reviewsCount: 145,
    rating: 4.2,
    preOrderStatus: false,
    imgs: [
      "https://res.cloudinary.com/di83yoe1d/image/upload/v1731052170/shopyournursery/adh7c7gl04oqqtnkzlwq.jpg",
      "https://res.cloudinary.com/di83yoe1d/image/upload/v1731052180/shopyournursery/m13qxjtzic6jnvdgrjis.png",
      "https://res.cloudinary.com/di83yoe1d/image/upload/v1731052193/shopyournursery/bflldlldvmdj8pslddgr.jpg",
      "https://res.cloudinary.com/di83yoe1d/image/upload/v1731052196/shopyournursery/c2pt8xyv0k5ykjg7pmbb.jpg",
    ],
  },
];
