// import Indoor from "../svgIcons/Indoor";
// import Outdoor from "../svgIcons/Outdoor";
// import Pet from "../svgIcons/Pet";

import { featuredPlants } from "./featuredPlants";
import { popularPlants } from "./popularPlants";

export const plantProducts = [...featuredPlants, ...popularPlants];
// export const plantProducts = [
//   {
//     id: 1,
//     title: "Snake Plant",

//     price: 20,
//     size: ["small", "medium", "large"],
//     place: "indoor",
//     placeIcon: <Indoor size={"18"} />,
//     tag: "best seller",
//     description: "A hardy indoor plant that can survive with minimal care.",
//     reviewsCount: 145,
//     rating: 4.7,
//   },
//   {
//     id: 2,
//     title: "Peace Lily",
//     price: 30,
//     size: ["medium", "large"],
//     place: "Pet Friendly",
//     placeIcon: <Pet size={18} />,
//     tag: "top rated",
//     description: "A beautiful flowering plant that thrives in shade.",
//     reviewsCount: 200,
//     rating: 4.9,
//   },
//   {
//     id: 3,
//     title: "Aloe Vera",
//     price: 40,
//     size: ["small", "medium"],
//     place: "outdoor",
//     placeIcon: <Outdoor size={"18"} />,
//     tag: "best seller",
//     description: "A versatile succulent known for its medicinal properties.",
//     reviewsCount: 185,
//     rating: 4.6,
//   },
//   {
//     id: 4,
//     title: "Fiddle Leaf Fig",
//     price: 60,
//     size: ["small", "medium", "large"],
//     place: "indoor",
//     placeIcon: <Indoor size={"18"} />,
//     tag: "top rated",
//     description: "A statement plant with large, beautiful leaves.",
//     reviewsCount: 320,
//     rating: 4.8,
//   },
//   {
//     id: 5,
//     title: "Spider Plant",
//     price: 70,
//     size: ["small", "large"],
//     place: "Pet Friendly",
//     placeIcon: <Pet size={18} />,
//     tag: "popular",
//     description: "A low-maintenance plant that's safe for pets.",
//     reviewsCount: 215,
//     rating: 4.5,
//   },
//   {
//     id: 6,
//     title: "Bamboo Palm",
//     price: 80,
//     size: ["small", "medium", "large"],
//     place: "indoor",
//     placeIcon: <Indoor size={"18"} />,
//     tag: "air purifier",
//     description: "An indoor palm that helps purify the air.",
//     reviewsCount: 275,
//     rating: 1.5,
//   },
//   {
//     id: 7,
//     title: "Lavender",
//     price: 100,
//     size: ["small", "medium", "large"],
//     place: "outdoor",
//     placeIcon: <Outdoor size={"18"} />,
//     tag: "best seller",
//     description: "A fragrant herb known for its calming properties.",
//     reviewsCount: 305,
//     rating: 2.5,
//   },
//   {
//     id: 8,
//     title: "Golden Pothos",
//     price: 120,
//     size: ["small", "medium", "large"],
//     place: "indoor",
//     placeIcon: <Indoor size={"18"} />,
//     tag: "easy care",
//     description: "A trailing plant that is easy to grow and maintain.",
//     reviewsCount: 165,
//     rating: 4.6,
//   },
//   {
//     id: 9,
//     title: "Rosemary",
//     price: 130,
//     size: ["large"],
//     place: "outdoor",
//     placeIcon: <Outdoor size={"18"} />,
//     tag: "top rated",
//     description: "A fragrant herb used in cooking and as an ornamental plant.",
//     reviewsCount: 225,
//     rating: 2.3,
//   },
// ];
